const BLOG_CATEGORIES = [
    'Technology',
    'Lifestyle',
    'Travel',
    'Education',
    'Personal',
    'Health',
    'Finance',
    'Food',
    'Entertainment',
    'Sports',
    'Science',
    'Art',
    'History',
    'Politics',
    'Culture',
    'Business',
    'Environment',
    'Fashion',
    'Music',
    'Photography',
    'Writing',
    'DIY',
    'Gaming',
    'Movies',
    'Books',
    'Health & Wellness',
    'Parenting',
    'Relationships',
    'Career',
    'Productivity',
    'Self-Improvement',
    'Travel & Adventure',
    'Technology & Gadgets',
    'Food & Cooking',
    'Sports & Fitness',
    'History & Culture',
    'Entertainment & Pop Culture',
    'Other'


]
export { BLOG_CATEGORIES };
